name = "esim-directory"
main = "src/index.ts"
compatibility_date = "2026-05-12"

[vars]
APP_ORIGIN = "http://localhost:8787"
SITE_NAME = "Global eSIM Directory"
JWT_ISSUER = "esim-directory"
BOOTSTRAP_ADMIN = "true"
BOOTSTRAP_ADMIN_EMAIL = "admin@example.com"
BOOTSTRAP_ADMIN_PASSWORD = "ChangeMe-Now!"
ACCESS_TOKEN_TTL_SECONDS = "900"
REFRESH_TOKEN_TTL_SECONDS = "2592000"

[[d1_databases]]
binding = "DB"
database_name = "esim_directory"
database_id = "adbb21e1-2973-429c-89ba-1258eb4305c0"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "KV"
id = "4997cf223c9e48239a7b9d07d6493351"

[[r2_buckets]]
binding = "R2"
bucket_name = "esim-directory-media"

[triggers]
crons = [ "*/5 * * * *" ]
